import type { Metadata, Viewport } from "next"
import localFont from "next/font/local"

import PlausibleProvider from "next-plausible"

import "./globals.css"

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans"
})
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono"
})

export const viewport: Viewport = {
  maximumScale: 1
}

export const metadata: Metadata = {
  title: "Carley | Nutrition Tracker",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.BASE_URL!)
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <PlausibleProvider
          domain={new URL(process.env.BASE_URL!).hostname}
          customDomain={process.env.PLAUSIBLE_CUSTOM_DOMAIN}
          selfHosted
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
